spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/everyletter_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: ckdckd
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          import_files: classpath:/sample.sql # DB 파일 명시적으로 선택
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor # 멀티 라인 입력 가능하도록
        connection:
          charSet: UTF-8 # 인코딩 설정
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

# 이메일 발송 정보
  mail:
    host: smtp.gmail.com
    port: 587
#    username: travelwithme.mail@gmail.com
    username: cccxhang001@gmail.com
#    password: puofrxedultxqtul
    password: ppntnbuaenhlcxse
    properties:
      mail:
        smtp:
          auth: true  #SMTP 서버 인증 여부 / Gmail은 서버 인증 요구하기 때문에 true
          starttls:
            enable: true  # SMTP서버가 TLS 사용하여 안전한 연결을 요구하는 경우 / TLS는 데이터를 암호화하여 안전한 전송 보장 프로토콜
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000  # 인증 코드 만료 시간 30분

# JWT 토큰 정보
jwt:
  token:
    secret: "secretKey"
    expiration: 60000
    refresh-token:
      expiration: 604800000

# 로그 레벨
logging:
  level:
    root: info
#server:
#  port: 8080
#  servlet:
#    context-path: /
#    encoding:
#      charset: UTF-8
#      enabled: true
#      force: true
#logging:
#  level:
#    me.silvernine: DEBUG