spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/everyletter_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: ckdckd
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          import_files: classpath:/sample.sql # DB 파일 명시적으로 선택
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor # 멀티 라인 입력 가능하도록
        connection:
          charSet: UTF-8 # 인코딩 설정
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
jwt:
  token:
    secret: "secretKey"
    expiration: 3600
    refresh-token:
      expiration: 86400

#server:
#  port: 8080
#  servlet:
#    context-path: /
#    encoding:
#      charset: UTF-8
#      enabled: true
#      force: true
#logging:
#  level:
#    me.silvernine: DEBUG